export default [
  {imgPath: "assets/images/Gallery/angel-1.jpg", className: "angel", description: "angel"},
  {imgPath: "assets/images/Gallery/angel-2.jpg", className: "angel", description: "angel"},
  {imgPath: "assets/images/Gallery/angel-3.jpg", className: "angel", description: "angel"},
  {imgPath: "assets/images/Gallery/angel-4.jpg", className: "angel", description: "angel"},
  {imgPath: "assets/images/Gallery/angel-warrior.jpg", className: "angel", description: "angel warrior"},
  {imgPath: "assets/images/Gallery/angel-warrior-2.jpg", className: "angel", description: "angel warrior"},
  {imgPath: "assets/images/Gallery/angel-warrior-3.jpg", className: "angel", description: "angel warrior"},
  {imgPath: "assets/images/Gallery/archangel-1.jpg", className: "angel", description: "archangel"},
  {imgPath: "assets/images/Gallery/archangel-2.jpg", className: "angel", description: "archangel"},
  {imgPath: "assets/images/Gallery/archangel-3.jpg", className: "angel", description: "archangel"},
  {imgPath: "assets/images/Gallery/archangel-4.jpg", className: "angel", description: "archangel"},
  {imgPath: "assets/images/Gallery/Death-Reaper_Brittney Hamilton.jpg", className: "angel", description: "death reaper"},
  {imgPath: "assets/images/Gallery/Death-Reaper-1.jpg", className: "angel", description: "death reaper"},
  {imgPath: "assets/images/Gallery/Death-Reaper-2.jpg", className: "angel", description: "death reaper"},
  {imgPath: "assets/images/Gallery/Battle-Dragon.jpg", className: "angel", description: "Battle dragon"},
  {imgPath: "assets/images/Gallery/Dragon-1.jpg", className: "angel", description: "dragon"},
  {imgPath: "assets/images/Gallery/DragonHead_Brittney Hamilton.jpg", className: "angel", description: "dragon head"},
  {imgPath: "assets/images/Gallery/elf-1.jpg", className: "angel", description: "elf"},
  {imgPath: "assets/images/Gallery/elf-2.jpg", className: "angel", description: "elf"},
  {imgPath: "assets/images/Gallery/elf-3.jpg", className: "angel", description: "elf"},
  {imgPath: "assets/images/Gallery/elf-4.jpg", className: "angel", description: "elf"},
  {imgPath: "assets/images/Gallery/Fairy-1.jpg", className: "angel", description: "fairy"},
  {imgPath: "assets/images/Gallery/Fairy-2.jpg", className: "angel", description: "fairy"},
  {imgPath: "assets/images/Gallery/Fairy-3.jpg", className: "angel", description: "fairy"},
  {imgPath: "assets/images/Gallery/Fairy-4.jpg", className: "angel", description: "fairy"},
  {imgPath: "assets/images/Gallery/Fairy-Brittney-Hamilton.jpg", className: "angel", description: "fairy"},
  {imgPath: "assets/images/Gallery/Fairy-2-Brittney-Hamilton.jpg", className: "angel", description: "fairy"},
  {imgPath: "assets/images/Gallery/frankenstein.jpg", className: "angel", description: "frankenstein"},
  {imgPath: "assets/images/Gallery/Vampire-1.jpg", className: "angel", description: "angel"},
  {imgPath: "assets/images/Gallery/Vampire-2.jpg", className: "angel", description: "angel"},
  {imgPath: "assets/images/Gallery/vampire-3.jpg", className: "angel", description: "angel"},
  {imgPath: "assets/images/Gallery/Vampire-4.jpg", className: "angel", description: "angel"},
  {imgPath: "assets/images/Gallery/Vampire-1-Brittney-Hamilton.jpg", className: "angel", description: "Vampire"},
  {imgPath: "assets/images/Gallery/Vampire-2-Brittney-Hamilton.jpg", className: "angel", description: "Vampire"},
  {imgPath: "assets/images/Gallery/Werewolf-Brittney-Hamilton.jpg", className: "angel", description: "Werewolf"},
  {imgPath: "assets/images/Gallery/werewolf-1-Brittney-Hamilton.jpg", className: "angel", description: "Werewolf"},
  {imgPath: "assets/images/Gallery/werewolf-2.jpg", className: "angel", description: "Werewolf"},
  {imgPath: "assets/images/Gallery/werewolf-3.jpg", className: "angel", description: "Werewolf"}
];
